/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#404758",
        "primary": "#006e2f",
        "on-primary-fixed": "#002109",
        "on-secondary-fixed": "#141b2b",
        "on-primary": "#ffffff",
        "secondary": "#575e70",
        "on-surface-variant": "#3d4a3d",
        "surface-variant": "#e1e3e4",
        "secondary-fixed": "#dce2f7",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-fixed": "#151c27",
        "tertiary": "#585f6c",
        "surface-container-lowest": "#ffffff",
        "background": "#f8f9fa",
        "inverse-primary": "#4ae176",
        "on-error-container": "#93000a",
        "surface-dim": "#d9dadb",
        "on-primary-container": "#004b1e",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface-tint": "#006e2f",
        "outline": "#6d7b6c",
        "on-tertiary-container": "#39404d",
        "surface-container-low": "#f3f4f5",
        "tertiary-container": "#a5acbb",
        "surface": "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "on-error": "#ffffff",
        "primary-fixed": "#6bff8f",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "outline-variant": "#bccbb9",
        "tertiary-fixed": "#dce2f3",
        "on-tertiary-fixed-variant": "#404754",
        "secondary-fixed-dim": "#c0c6db",
        "inverse-surface": "#2e3132",
        "secondary-container": "#d9dff5",
        "primary-container": "#22c55e",
        "surface-container": "#edeeef",
        "tertiary-fixed-dim": "#c0c7d6",
        "on-background": "#191c1d",
        "primary-fixed-dim": "#4ae176",
        "surface-bright": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#5c6274",
        "on-primary-fixed-variant": "#005321",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        lg: "24px",
        md: "16px",
        xl: "32px",
        margin: "32px",
        xxl: "48px",
        gutter: "24px",
        sm: "8px",
        base: "4px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-md": ["Geist"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "label-sm": ["Geist"],
        "headline-md": ["Hanken Grotesk"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
