"""Create dashboard_complaint_workflows table

Revision ID: 07827f2f3830
Revises: 400737c1b0b9
Create Date: 2026-06-26 15:55:51.109083

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07827f2f3830"
down_revision: Union[str, Sequence[str], None] = "400737c1b0b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_complaint_workflows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("complaint_id", sa.UUID(), nullable=False),
        sa.Column("internal_status", sa.String(length=50), nullable=False),
        sa.Column("assigned_admin_id", sa.UUID(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_admin_id"], ["dashboard_admin_users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dashboard_complaint_workflows_complaint_id"),
        "dashboard_complaint_workflows",
        ["complaint_id"],
        unique=True,
    )
    # ### end Alembic commands ###

    # Enable Row Level Security (RLS) on all dashboard-owned tables
    op.execute("ALTER TABLE public.dashboard_admin_users ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE public.dashboard_ai_analysis ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE public.dashboard_audit_logs ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE public.dashboard_settings ENABLE ROW LEVEL SECURITY;")
    op.execute(
        "ALTER TABLE public.dashboard_complaint_workflows ENABLE ROW LEVEL SECURITY;"
    )

    # Create explicit deny policies for client-side API roles (anon, authenticated)
    op.execute(
        'CREATE POLICY "Deny all client-side access" ON public.dashboard_admin_users FOR ALL TO anon, authenticated USING (false);'
    )
    op.execute(
        'CREATE POLICY "Deny all client-side access" ON public.dashboard_ai_analysis FOR ALL TO anon, authenticated USING (false);'
    )
    op.execute(
        'CREATE POLICY "Deny all client-side access" ON public.dashboard_audit_logs FOR ALL TO anon, authenticated USING (false);'
    )
    op.execute(
        'CREATE POLICY "Deny all client-side access" ON public.dashboard_settings FOR ALL TO anon, authenticated USING (false);'
    )
    op.execute(
        'CREATE POLICY "Deny all client-side access" ON public.dashboard_complaint_workflows FOR ALL TO anon, authenticated USING (false);'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Drop RLS policies
    op.execute(
        'DROP POLICY IF EXISTS "Deny all client-side access" ON public.dashboard_complaint_workflows;'
    )
    op.execute(
        'DROP POLICY IF EXISTS "Deny all client-side access" ON public.dashboard_settings;'
    )
    op.execute(
        'DROP POLICY IF EXISTS "Deny all client-side access" ON public.dashboard_audit_logs;'
    )
    op.execute(
        'DROP POLICY IF EXISTS "Deny all client-side access" ON public.dashboard_ai_analysis;'
    )
    op.execute(
        'DROP POLICY IF EXISTS "Deny all client-side access" ON public.dashboard_admin_users;'
    )

    # Disable RLS
    op.execute(
        "ALTER TABLE public.dashboard_complaint_workflows DISABLE ROW LEVEL SECURITY;"
    )
    op.execute("ALTER TABLE public.dashboard_settings DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE public.dashboard_audit_logs DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE public.dashboard_ai_analysis DISABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE public.dashboard_admin_users DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dashboard_complaint_workflows_complaint_id"),
        table_name="dashboard_complaint_workflows",
    )
    op.drop_table("dashboard_complaint_workflows")
    # ### end Alembic commands ###
